
GET http://localhost:5000/api/test

###
GET http://localhost:5000/api/signout

###

POST http://localhost:5000/api/signup

Content-Type: application/json

{
    "lol":12
}

###

POST http://localhost:5000/api/signin